### ISSUE TITLE
Might I suggest a coalition with Constructs Armory,

### ISSUE THREAD

**Issue by Thunder-Nova** [Landmaster/PlusTiC#197] opened 2018-06-05 18:14 UTC
It is another TiCon addon, yet it's a mod that adds armor and such would like to see if possible to implement it.

I also made a suggestion for modifiers on his issue page yet doesn't want to implement it. Though since you are using materials of various mods, hopefully you can implement it, if possible.

https://github.com/TheIllusiveC4/ConstructsArmory/issues/55
<details>
  <summary>Click to expand</summary>
Yea, another suggestion sorry, though just though of it, and mostly want an opinion with it as well.

## Story
When I was playing the All The Mods 3 modpack, I was playing around in making jetpacks and then when I saw the armored Jetpacks, with my current Armor on myself, I was thinking. Why not.

Then I remember when Tinker had modifiers that existed with a required mod, but doesn't force to have such mods. So hoping it would be possible to make it that way as well.

## Suggestion

Note: The Modifiers Act as **Accessory**, meaning the 1 accessory rule applies to them. To avoid making the armor overpowered, with a few exception depending on the mod original intention.

 - Jetpack (Tier)
**Mods**: Mekanism / Simply Jetpack
Uses a Jetpack to permanantly be added as an Accessory modifier for the chestplate.  With the RF 1/2 of the used Jetpack.

- RF Boost (Tier) (Not accessory):
**Mods**: Ender IO / Draconic Evolution / Immersive Engineering / Thermal Expansion
The armor will act as a portable battery, it won't affect durability, nor defence. But can charge items on the toolbar, and body. This modifier is upgradable, with a higher tier Capacitor. If the mod author can make it possible to make the level of the RF of the capacitor used.

- Solar:
**Mods**: Ender IO / Actually Additions / Mekanism Generators / Tech Reborn
Uses Solar Panel as an Accessory modifier for the helmet. Like the jetpack, it holds half the RF, but will make as much RF as the solar power.

- Goggles of Revealing
**Mod**: Thaumcraft
Pretty much self explanatory, but an Accessory modifier using the Goggles of Revealing for the helmet, won't have the vis discount.

- Apiarist
**Mod**: Forestry
Uses the Apiarist armor of Forestry as Accessory Modifier for their respective armor. Respectively gives the effect of an Apiarist.

- Probing
**Mod**: The One Probe
A non-accessory Modifier, that uses The One Probe. Pretty much self explanatory on it's effect. (only need 1)

If anyone wants to add to the suggestion feel free, but don't forget to add the Mods that it uses. Usually to avoid making the author search for them.
</details>

**Comment by Landmaster** [comment] 2018-06-05 20:02
Duplicate of #175

**Closed by Landmaster** 2018-06-05 20:02 UTC
