### ISSUE TITLE
conflict between plustic and NaturalPledge

### ISSUE THREAD

**Issue by scalda** [Landmaster/PlusTiC#19] opened 2017-03-31 10:22 UTC
Hi i will be posting this on the NaturalPledge issues page aswell.

But there is an issue where your mod is trying to register manasteel to tinkers when plustic already has, please see the crash report attached.

[crash-2017-03-31_11.18.34-client.txt](https://github.com/yrsegal/NaturalPledge/files/885261/crash-2017-03-31_11.18.34-client.txt)

Regards
Scalda
(Lead dev for FoolCraft)

**Comment by Landmaster** [comment] 2017-03-31 11:55
duplicate of #16, #2, and yrsegal/NaturalPledge#27

**Closed by Landmaster** 2017-03-31 11:55 UTC
