### ISSUE TITLE
Crash when breaking exu2 enchanter with pickaxe with global traveller

### ISSUE THREAD

**Issue by EgbertMedia** [Landmaster/PlusTiC#180] opened 2018-05-06 14:16 UTC
My server crashed when someone tried to break a Exu2 enchanter with a plustic pickaxe with the global traveller. We are playing the ATM3 modpack.

Here's a gist with the crashlog
https://gist.github.com/EgbertMedia/c7c96b58a387c98c79d7cf90b669cf33

**Comment by Landmaster** [comment] 2018-05-07 11:26
duplicate of #149

**Closed by Landmaster** 2018-05-07 11:26 UTC
