### ISSUE TITLE
crash on 1.12

### ISSUE THREAD

**Issue by TandJ21** [Landmaster/PlusTiC#71] opened 2017-07-20 04:01 UTC
[crash-2017-07-20_04.41.49-client.txt](https://github.com/Landmaster/PlusTiC/files/1161097/crash-2017-07-20_04.41.49-client.txt)

**Comment by TandJ21** [comment] 2017-07-20 04:01
with latest version of tinkers

**Comment by Landmaster** [comment] 2017-07-20 15:13
duplicate of #70

**Closed by Landmaster** 2017-07-20 15:13 UTC
Labels: bug, unstable version
