### ISSUE TITLE
[1.10.2] Natural Pledge compat. (Manasteel register)

### ISSUE THREAD

**Issue by DeadSix27** [Landmaster/PlusTiC#2] opened 2017-02-12 16:10 UTC
Server Crashes due to PlusTiC trying to register manasteel as well as [Natural Pledge](https://minecraft.curseforge.com/projects/natural-pledge).

```
[17:01:20] [Server thread/ERROR] [FML/]: Caught exception from Natural Pledge (botanicaladdons) java.lang.ExceptionInInitializerError
	at shadowfox.botanicaladdons.common.integration.tinkers.TinkersIntegration.load(TinkersIntegration.kt:21) ~[TinkersIntegration.class:?]
	.......
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "manasteel": It was already registered by PlusTiC
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:822) ~[TinkerRegistry.class:?]
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:128) ~[TinkerRegistry.class:?]
	at slimeknights.tconstruct.library.MaterialIntegration.integrate(MaterialIntegration.java:116) ~[MaterialIntegration.class:?]
	at shadowfox.botanicaladdons.common.integration.tinkers.TinkersMaterials.<init>(TinkersMaterials.kt:168) ~[TinkersMaterials.class:?]
	at shadowfox.botanicaladdons.common.integration.tinkers.TinkersMaterials.<clinit>(TinkersMaterials.kt:34) ~[TinkersMaterials.class:?]
	... 37 more
```

**Comment by Landmaster** [comment] 2017-02-12 17:15
@DeadSix27 Confirmed that it crashes, but it works fine if Botania integration is disabled in the config for PlusTiC so that the other features of this mod can be used without breaking Natural Pledge. If you want to use my Botania tools instead of those of Natural Pledge, you should open up an issue on [their GitHub page](https://github.com/yrsegal/NaturalPledge/issues) so that they can add a config parameter to disable their Botania integration. Otherwise, since this is easily fixed by a config change, I am closing this.

**Closed by Landmaster** 2017-02-12 17:15 UTC

**Comment by DeadSix27** [comment] 2017-02-12 17:26
No way to co-exist? E.g making either of the mods work with the others manasteel etc?

**Comment by Landmaster** [comment] 2017-02-12 17:41
@DeadSix27 Even if our manasteel is registered under different names, Tinkers Construct would not be able to decide which material to use (or one would override the other). In order for both manasteels to coexist, they would either have to use different materials (in which case one of them will no longer be manasteel), or there would have to be another addon mod for TiC that would enable one to choose between two different materials (possibly with a selection list).
