### ISSUE TITLE
Random crash upon loading up my world (1.12.2)

### ISSUE THREAD

**Issue by RedBullSlurpie** [Landmaster/PlusTiC#160] opened 2018-02-22 02:08 UTC
Just a random crash, not entirely sure what caused it. I've un-loaded and loaded the world many times before, and this was just random. 1st i've seen it happen, so again, not sure what caused it, but upon loading the world again, all is fine. Here is the crash log it generated in-case it's something I have in my world that's causing it, or something in the mod. 

Edit: Playing my custom pack, if you need anything else, let me know.
Mod version-  plustic-6.3.6.2
Forge version- 14.23.2.2611

https://pastebin.com/Qw5v6DXg

**Comment by Landmaster** [comment] 2018-02-22 02:15
Duplicate of #159

**Closed by Landmaster** 2018-02-22 02:15 UTC
