### ISSUE TITLE
Crash with EnderIO

### ISSUE THREAD

**Issue by DEFALTPANDA** [Landmaster/PlusTiC#173] opened 2018-04-02 16:22 UTC
While adding the newly release version of EnderIO I got this crash with plustic version 6.3.7.0.
https://pastebin.com/WBapZLaN

**Comment by DEFALTPANDA** [comment] 2018-04-02 16:22
And yes the modpack works fine without EnderIO

**Comment by 47delasPECII** [comment] 2018-04-02 18:55
My guess is that plustic tries to make tconstruct tools (like tool binding, hammer head, pickaxe head etc) from the new metals added by Ender IO and then the mods crushes. He just need to add ender io support.

**Comment by Landmaster** [comment] 2018-04-02 19:06
This is the ***fourth*** duplicate of #168 I have gotten so far. **Read [CONTRIBUTING.md](../blob/1.12/CONTRIBUTING.md) *before* you post!**

**Closed by Landmaster** 2018-04-02 19:06 UTC
