### ISSUE TITLE
[Suggestion] Constructs Armory Support

### ISSUE THREAD

**Issue by KIdWither** [Landmaster/PlusTiC#184] opened 2018-05-19 03:32 UTC
Constructs armory adds in tcon armors, would be cool to see some materials added in by this mod to be there. 
Link to mods GitHub: https://github.com/TheIllusiveC4/ConstructsArmory/issues?q=is%3Aopen+is%3Aissue

**Comment by YaibaToKen** [comment] 2018-05-19 16:47
Duplicate of #175 and #181

**Closed** 2018-05-19 21:06 UTC

**Comment by Landmaster** [comment] 2018-05-20 01:07
Now that the mod has stabilized to beta (it appears), I will look into support for it.
