### ISSUE TITLE
Can't use Shield with Katana

### ISSUE THREAD

**Issue by InjuredWolf** [Landmaster/PlusTiC#42] opened 2017-05-31 04:55 UTC
Does the katana have a right-click ability of some kind? I can't use a shield in my offhand when I have a katana in my main hand.

**Comment by Landmaster** [comment] 2017-05-31 11:18
duplicate of #39

**Closed by Landmaster** 2017-05-31 11:18 UTC

**Comment by vrork** [comment] 2017-05-31 19:12
Can we get a config option to allow the use of shields alongside katanas please?

**Comment by Landmaster** [comment] 2017-05-31 19:39
@vrork @InjuredWolf **No, for the same reason that the cleaver in vanilla Tinkers Construct disables shield use: it is a two-handed weapon. It's a balance thing :)**

**Comment by vrork** [comment] 2017-05-31 19:49
https://www.reddit.com/r/SWORDS/comments/3ba2l3/are_katana_swords_1h_or_2h/
