### ISSUE TITLE
Crash with Ender IO

### ISSUE THREAD

**Issue by TheSnowyChickens** [Landmaster/PlusTiC#170] opened 2018-04-01 21:40 UTC
Hello,

MC crash with the today released Ender IO version.
The Error say : Description: There was a severe problem during mod loading that has caused the game to fail net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PlusTiC (plustic)

[crash-2018-04-01_23.38.26-client.txt](https://github.com/Landmaster/PlusTiC/files/1866730/crash-2018-04-01_23.38.26-client.txt)

MC 1.12.2
Forge ...51
Plustic 6.3.7.0
Ender IO 5.0.20
Ender Core 0.5.18

**Comment by Landmaster** [comment] 2018-04-01 21:45
duplicate of #168

**Closed by Landmaster** 2018-04-01 21:45 UTC
Labels: duplicate
