### ISSUE TITLE
Crash due to a java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by dmodoomsirius** [Landmaster/PlusTiC#129] opened 2017-12-03 03:22 UTC
https://gist.github.com/dmodoomsirius/e8afbb2662a98ce9dcdbe0c59ce97203

**Comment by Landmaster** [comment] 2017-12-03 20:43
Steps to reproduce?

**Comment by Landmaster** [comment] 2018-01-29 03:22
Closing because this appears to be the fault of a coremod that is completely unrelated to PlusTiC and its dependencies.

**Closed by Landmaster** 2018-01-29 03:22 UTC
Labels: can’t reproduce
