### ISSUE TITLE
Bug when player dies

### ISSUE THREAD

**Issue by jojati** [Landmaster/PlusTiC#333] opened 2019-11-23 17:07 UTC
I selected every single mod of my private pack, so it's PlusTiC that causes a huge issue.

/kill @p sends me a red error message in the chat

unequip armor and lay in lava crashes my game.

when I guit the title after playing, the whole game crashes. Logs will follow

**Comment by Landmaster** [comment] 2020-03-28 00:31
I believe this is a duplicate of an issue that has since been fixed

**Closed by Landmaster** 2020-03-28 00:31 UTC
