### ISSUE TITLE
Advent of Ascension support!

### ISSUE THREAD

**Issue by mrcakesamurai** [Landmaster/PlusTiC#270] opened 2019-03-02 02:18 UTC
A huge mod which I've grown to love and appreciate! ExtraTiC supported this mod before in 1.7.10, and it would be amazing if it was updated to the 1.12.2 version!

**Comment by Landmaster** [comment] 2019-03-02 15:37
Duplicate of #268

**Closed by Landmaster** 2019-03-02 15:37 UTC
