### ISSUE TITLE
1.10.2 Actually Additions items not showing up

### ISSUE THREAD

**Issue by dakoko** [Landmaster/PlusTiC#150] opened 2018-02-02 09:52 UTC
Actually Additions crystals dont show up (in the tinkers book) and can't be used to make tool parts.

**Comment by Landmaster** [comment] 2018-02-02 12:24
Duplicate of #87, please update.

**Closed by Landmaster** 2018-02-02 12:24 UTC

**Comment by dakoko** [comment] 2018-02-02 12:38
I was and am using the newest version that 1.10.2 has (5.2.1.3) and it isn't working. I tried the 1.12.2 version and it worked perfectly. 
![image](https://user-images.githubusercontent.com/36070476/35733588-a2851db6-0826-11e8-9195-4789c6564271.png)

**Comment by dakoko** [comment] 2018-02-02 12:55
So are you saying that i should update past the newest version for 1.10.2 or i should play on 1.12.2 which i cannot do due to the fact that tropicraft isnt in it. (And no the bug isnt only limited to the modpack that has tropicraft in it but also bare bones packs that only have tinkers, plustic, actually additions and the supportmods like chickencode lib)

**Comment by Landmaster** [comment] 2018-02-02 19:46
What version of Actually Additions are you using?

**Comment by dakoko** [comment] 2018-02-03 06:41
Im using the r105 version of AA which is the newest one they've got for 1.10.2. (The update is old though, it was uploaded on march 12th 2017)

**Comment by Landmaster** [comment] 2018-02-04 14:36
@dakoko PlusTiC does not add the other Act. Add. materials before MC 1.12.
