### ISSUE TITLE
PlusTIC Crash upon loadup

### ISSUE THREAD

**Issue by ElectricBlue1** [Landmaster/PlusTiC#52] opened 2017-06-15 19:51 UTC
I recently updated PlusTIC to 5.0.1.4 on 1.10 and the pack i'm running it on is a custom and hasn't crash with this mod in particular until this update. Here the log https://pastebin.com/xbwN57TJ

**Comment by Landmaster** [comment] 2017-06-15 20:15
duplicate of #51

**Closed by Landmaster** 2017-06-15 20:15 UTC

**Comment by Landmaster** [comment] 2017-06-15 20:17
@ElectricBlue1 **Update Chisel.**
