### ISSUE TITLE
Cannot create a fluidstack from a null fluid -plustic-6.0.0.4 - 1.12

### ISSUE THREAD

**Issue by Furuchiru** [Landmaster/PlusTiC#81] opened 2017-07-30 17:39 UTC
https://pastebin.com/VgGpH5dw

**Comment by Landmaster** [comment] 2017-07-31 00:25
**Are you seriously opening the third duplicate of #79?! Search issues *before* you post!**

**Closed by Landmaster** 2017-07-31 00:25 UTC
