### ISSUE TITLE
Laser Smelting Double Stone Slabs into Charcoal 

### ISSUE THREAD

**Issue by popemichael** [Landmaster/PlusTiC#143] opened 2018-01-18 03:26 UTC
The laser is smelting double stone slabs into charcoal.

Tested in All the Mods 3 1.12.2 v5.7b

1. Make 2 stone slabs
2. Place one slab on top of another to make a whole block
3. Take a laser (any laser) and put it into block smelting mode
4. Fire the laser at the block

Charcoal comes out.

**Comment by Landmaster** [comment] 2018-01-19 14:47
What block is beneath the stone slabs?

**Comment by popemichael** [comment] 2018-01-19 19:20
The two that I can say for sure is a grass block and a dirt block. The reason being that I discovered it on the issue while using the "Lost Cities" world type in "all the mods 3"

The only place where the double stone slabs naturally occur is on top of the dirt and the grass blocks.

**Comment by Landmaster** [comment] 2018-01-28 00:54
First, try reproducing with only Mantle, Tinkers Construct, and PlusTiC. If that does not reproduce the issue, add the Lost Cities mod in and see if the issue appears then.

**Comment by Landmaster** [comment] 2018-04-09 21:45
Closing due to lack of information for over 2 months.

**Closed by Landmaster** 2018-04-09 21:45 UTC
Labels: can’t reproduce
